# Generated by Django 4.2.4 on 2023-08-12 12:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=datetime.datetime(2023, 8, 12, 12, 42, 28, 345663, tzinfo=datetime.timezone.utc), verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('first_name', models.CharField(max_length=64, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=64, verbose_name='Фмилия')),
                ('age', models.PositiveSmallIntegerField(verbose_name='Возраст')),
                ('status', models.CharField(blank=True, choices=[('N', 'Новый заказчик'), ('O', 'Обычный заказчик'), ('R', 'Постоянный заказчик')], default='N', max_length=64, null=True, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Заказчик',
                'verbose_name_plural': 'Заказчики',
                'db_table': 'customer_profile',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=datetime.datetime(2023, 8, 12, 12, 42, 28, 345663, tzinfo=datetime.timezone.utc), verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('title', models.CharField(max_length=125, verbose_name='Название')),
                ('duration', models.IntegerField(verbose_name='Продолжительность (дней)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
                'db_table': 'event',
            },
        ),
        migrations.CreateModel(
            name='MasterProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=datetime.datetime(2023, 8, 12, 12, 42, 28, 345663, tzinfo=datetime.timezone.utc), verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('first_name', models.CharField(max_length=64, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=64, verbose_name='Фмилия')),
                ('age', models.PositiveSmallIntegerField(verbose_name='Возраст')),
                ('education', models.CharField(blank=True, choices=[('ST', 'Самоучка'), ('TC', 'Курсы подготовки'), ('SE', 'Среднее специальное'), ('HE', 'Высшее')], default=None, max_length=125, null=True, verbose_name='Образование')),
            ],
            options={
                'verbose_name': 'Мастер',
                'verbose_name_plural': 'Мастера',
                'db_table': 'master',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=datetime.datetime(2023, 8, 12, 12, 42, 28, 345663, tzinfo=datetime.timezone.utc), verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('title', models.CharField(max_length=125, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Навык',
                'verbose_name_plural': 'Навыки',
                'db_table': 'skill',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=datetime.datetime(2023, 8, 12, 12, 42, 28, 345663, tzinfo=datetime.timezone.utc), verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('title', models.CharField(max_length=125, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('reward', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Вознаграждение')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='facilities_area.event', verbose_name='Мероприятие')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
                'db_table': 'task',
            },
        ),
        migrations.CreateModel(
            name='MasteryOfSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=datetime.datetime(2023, 8, 12, 12, 42, 28, 345663, tzinfo=datetime.timezone.utc), verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('years_experience', models.PositiveSmallIntegerField(default=0, verbose_name='Опыт (годы)')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facilities_area.masterprofile', verbose_name='Мастер')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facilities_area.skill', verbose_name='Умение')),
            ],
            options={
                'verbose_name': 'Владение навыком',
                'verbose_name_plural': 'Владение навыками',
                'db_table': 'mastery_of_skill',
                'unique_together': {('skill', 'master')},
            },
        ),
        migrations.AddField(
            model_name='masterprofile',
            name='skills',
            field=models.ManyToManyField(blank=True, null=True, related_name='master_profiles', through='facilities_area.MasteryOfSkill', to='facilities_area.skill', verbose_name='Умения'),
        ),
    ]
